### ISSUE TITLE
Demos not working

### ISSUE THREAD

**Issue by yxliang01** [SidebarJS/sidebarjs#3]
When I use the demo pages to access `github.com`, they all give me an `alert` saying that "for security reason, framing is not allowed."

Thanks

**Comment by lorenzodianni** [comment]
Did you clone the repo or did you try on github?

Try [Demo](https://rawgit.com/SidebarJS/sidebarjs/master/demo/index.html)

**Comment by yxliang01** [comment]
Hmm it is different now. Do the commits you made just now change the demos' behavior? Since few hours ago, when I click those links, it will either be blank or get the warning prompt. I was just using the demo links.

Thanks

**Comment by lorenzodianni** [comment]
Yes, it was probably my fault.
Wrong export, now should work correctly ;)

Thanks!
