### ISSUE TITLE
[question] Why are you not using the data-* prefix?

### ISSUE THREAD

**Issue by hdl-helsinki** [SidebarJS/sidebarjs#4]
Html validators fails because the `sidebarjs` prefix is "not allowed": https://html5.validator.nu/?doc=https%3A%2F%2Fcdn.rawgit.com%2FSidebarJS%2Fsidebarjs%2Fmaster%2Fdemo%2Findex.html

Is there a reason to not use the `data-*` prefix?

Thank you.

**Comment by lorenzodianni** [comment]
Hi, i'm sorry for the delay!
Attributes with data-* is just a formal limitation/restriction, you haven't a real pro/con.
Maybe in the future i'll prefix the attributes with data-* to make them HTML validator compliant.

Thanks!
