### ISSUE TITLE
Bad mobile experience

### ISSUE THREAD

**Issue by free-easy** [SidebarJS/sidebarjs#8]
I'm currently developing a webapp with angular material, which has a sidenav component, but it doesn't support swipe gesture yet.

I've tried `sidebarjs` but it doesn't feel as smooth as a native sidebar on mobile (tested on Huawei P8 lite: Chrome 61.0.3168.98).

I've also tried [materialize's implementation of sidenav](http://materializecss.com/mobile.html)
and it feels more "native". But since I'm already using angular material, I don't want to introduce another
CSS framework, which will for sure cause some conflict.

So `sidebarjs` would be the perfetct choice for me, since it's a single, isolated component.
But, is there any way to improve its smoothness?

**Comment by lorenzodianni** [comment]
I'm sorry but i can't test it on Huawei P8 lite

Try to
* upgrade chrome to latest version
* tell me how many FPS do you have on swipe action
* provide me a GIF

**Comment by free-easy** [comment]
Hi. I've upgraded chrome to the latest version (63.0.3239.111) and tried to measure the FPS.
Well with `sidebarjs` when the FPS is around 30 when I swipe the sidebar.
I've tried with the Materialize's sidenav as well and that performed 50 FPS more or less.

Sorry but I can't give any GIF, since with a screen recorder my phone gets super-laggy...

**Comment by lorenzodianni** [comment]
Hi @free-easy, thanks for these info!

Sidebarjs seems to be more performant if it has only 30 FPS, so without debugging i've not idea.
I'll try to find a Huawei P8 lite where debug it, meanwhile i can't help you, i'm sorry.

I'll let you know if I have more news about it, thank you!
