### ISSUE TITLE
Rright swip close the (left) panel

### ISSUE THREAD

**Issue by Smiley32** [SidebarJS/sidebarjs#9]
I do not understand why a right swip close a left panel.

And with that, a strange behavior occurs on big screen:

![bug](https://user-images.githubusercontent.com/17594526/40701503-6be15da6-63de-11e8-8bbc-3d4c6719801e.gif)

Maybe it has to do with the possibility of a right panel, but in this case, it should be better to replace the abs with a condition on left/right

**Comment by lorenzodianni** [comment]
Fixed, thank you! 🎉
